name: flutter_project
description: 'A new Flutter project.'
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  basic_utils: ^5.7.0
  ikchatbot: ^1.0.5
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_settings_screen_ex: ^0.0.1+5
  firebase_storage: ^11.6.9
  image_picker: ^1.1.0
  cloud_firestore: ^4.15.8
  firebase_app_check: ^0.2.1+17
  dash_chat_2: ^0.0.20
  http: ^1.2.0
  provider: ^6.1.2
  uuid: ^4.3.3
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.13.1'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'asset/logo.png'
  flutter_lints: ^3.0.1

# For information oflutter pub add httpn the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/login_bg1.jpg
    - asset/login_bg2.jpg
    - asset/login_bg4.png
    - asset/login_bg3.jpg
    - asset/arc.jpg
    - asset/ir.jpg
    - asset/logo.png
    - asset/logo1.png
    - asset/profile.png
    - asset/bg_img.jpg
    - asset/bg_img1.jpg
    - asset/bg_img2.jpg
    - asset/bg_img4.png
    - asset/iot.png
    - asset/culturals.png
    - asset/workshop.png
    - asset/flutter.png
    - asset/culturals.png
    - asset/chatbg.png
    - asset/extra.png
    - asset/fullstack.png
    - asset/chatclr.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
